### ISSUE TITLE
simplezabbix: cannot import name VariableManager

### ISSUE THREAD

**Issue by slashterix** [openshift/openshift-tools#3128]
```
Traceback (most recent call last):
  File "/usr/bin/ops-zagg-metric-processor", line 36, in <module>
    from openshift_tools.ansible.simplezabbix import SimpleZabbix
  File "/usr/lib/python2.7/site-packages/openshift_tools/ansible/simplezabbix.py", line 27, in <module>
    from ansible.vars import VariableManager
ImportError: cannot import name VariableManager
```

**Comment by slashterix** [comment]
I think this is all it needs to work, testing now.
```
diff --git a/openshift_tools/ansible/simplezabbix.py b/openshift_tools/ansible/simplezabbix.py
index d6370c2..6a326cd 100644
--- a/openshift_tools/ansible/simplezabbix.py
+++ b/openshift_tools/ansible/simplezabbix.py
@@ -24,7 +24,7 @@ the existing Ansible zabbix modules.
 import json
 from collections import namedtuple
 from ansible.parsing.dataloader import DataLoader
-from ansible.vars import VariableManager
+from ansible.vars.manager import VariableManager
 from ansible.inventory import Inventory
 from ansible.playbook.play import Play
 from ansible.executor.task_queue_manager import TaskQueueManager
```

http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html#python-api-2-0

**Comment by slashterix** [comment]
This might be related to me building on `rhel7:latest` instead of `rhel7:7.3-97`

**Comment by slashterix** [comment]
Also needs Inventory changed to InventoryManager, see https://github.com/slashterix/openshift-tools/commit/2cf467a45762d1f83c625474484c645e1016a017

**Comment by ivanhorvath** [comment]
Thanks for bringing this to our attention. We haven't run into this yet because we haven't rebuilt that bit in a long time. I imagine this has more to do with ansible version, or rather ansible lib version than rhel version. The reason we went back to 7.3 was a yum issue where between runs of yum it would forget all repos.
